### ISSUE TITLE
Use of U+00A1   INVERTED EXCLAMATION MARK

### ISSUE THREAD

**Issue by r12a** [w3c/elreq#90]
2.2.1 Ethiopicized Punctuation
http://w3c.github.io/elreq/#ethiopicized_punctuation

i'm curious about how and when  ¡ is used in ethiopic, and whether U+00BF   INVERTED QUESTION MARK     ¿ is also used (as in Spanish). The latter isn't in the list.

**Comment by dyacob** [comment]
¡ is used in Ethiopic at the end of a sentence as a "sarcasm mark", it has the special name "Timherte Slaq" in Amharic.  Not seen so frequently in literature, more often in political comics (example at the link below).  ¿ is not known to be used in Amharic.  It is not in the ES-781:2002/2014 punctuation inventory.

https://www.flickr.com/photos/79628563@N00/14917188759/in/album-72157647046359086/

Should an explanatory sentence be added to 2.2.1 regarding inverted exclamation mark?

**Comment by r12a** [comment]
> Should an explanatory sentence be added to 2.2.1 regarding inverted exclamation mark?

yeah, i think that would be really useful.

**Comment by r12a** [comment]
@dyacob do think you'd be able provide me with an example sentence that uses this, as text, here?  You could write the text from your flickr example here, if that's easiest, or provide me with another sentence that uses it. Either would work.  Thanks.

**Comment by r12a** [comment]
Oh, and a translation would be nice.

**Comment by dyacob** [comment]
Yes, I'll review some examples and will post back here with translation.

**Comment by dyacob** [comment]
Timherte Slaq... definitely a curiosity in that everyone seems to know of it, but also not use it in practice.  It might be due to a keyboard inconvenience, most samples that I've seen of it have been handwritten such as in the editorial cartoon.  I do recall coming into this past year in print, but unfortunately did not note the reference.  I'll definitely note it when I come into it next.

I did scan a number of political cartoons where it is found, like the one from flickr in this thread.  The text:

የበሰውን
ያንተን ክልክለኸኝ
ብቻህን ብትበላም
እኔ ግን የጀኔን
አበላሃለሁ¡

Translation:

"You could not give me your cooked one but I will feed you mine from my hand."

The two figures are Meles Zenawi of Ethiopia eating roasted corn, and speaking next to him is Isayas Afeworki of Eritrea.  "Cooked one" is idiomatic and probably will mean something other than food, like "opportunity", or something that has been prepared or constructed.

![Zegabi251090](https://user-images.githubusercontent.com/8098333/201541997-14859631-d798-4072-b228-f9fd3563dc3a.jpg)

This came from the Zegabi newspaper Senie 10 1990 EC  (June 17, 1998 GC)
ዘጋቢ ፣ ሰኔ 10 ቀን ፲፱፻፺
